Se creó la entidad de Libro
Franklizcano/FirstAPI pull request #7
Opened 2021-04-23 17:38 UTC by Franklizcano

Está conectada con mysql

2021-04-23 23:24 UTC, dariojg requested changes

2021-04-23 23:24 UTC, dariojg commented on PATH/FICHERO.LOG APP.JAR
> +2021-04-23 12:36:26.820  INFO 44874 --- [SpringContextShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
@Franklizcano  no te lo habia dicho pero los archivos .jar no deben subirse a github,  tenes que agregarlos al .gitignore, todo lo que agregues al archivo ".gitignore" no se va a commitear, acá te dejo una referencia por si queres investigar https://git-scm.com/docs/gitignore. y lo mismo para los .log y otros files que no son propios del proyecto

2021-04-23 23:24 UTC, dariojg commented on src/main/resources/application.properties
> +spring.datasource.password = 123456Aa*.5
esto ahora está bien, en un futuro no deberiamos subir datos secretos o sensibles a github.

2021-04-27 14:04 UTC, Franklizcano commented on PATH/FICHERO.LOG APP.JAR
> +2021-04-23 12:36:26.820  INFO 44874 --- [SpringContextShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
Perfecto Dario, ahí lo modifiqué en los siguientes commits

2021-04-27 16:26 UTC, dariojg approved these changes

2021-04-27 16:26 UTC, merged